# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 914932848d60459328287bc047e8619ae091408dc9929abf548467078a22fa5b203540725928bced52617305962b6755ff14ef4fc058f94366c54dcb58f1f28d

test:
  secret_key_base: 8f39c071a2eecc36fc35f1b0f6dab8aa80814281d4f366879fd917fe4e5e6232333055cd42e1976d6bcd6a5b345b35b6dedb3b9b2fd8c0c0e8dec89c01151650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
